### ISSUE TITLE
responsive for different screen sizes

### ISSUE THREAD

**Issue by lishenyu16** [HerbertHe/for-editor-herb#3]
I saw that it's working fine for mobile device, but still for some sizes of screen, it's not quite responsive, here I attached a screenshot:
![image](https://user-images.githubusercontent.com/16713047/79036709-cdadbd80-7b7f-11ea-8ce2-31988c7a6783.png)

when screen width **>900 px**, it becomes not responsive.

**Comment by lishenyu16** [comment]
I see the issue, could you make the css for 'for-toolbar > for-pc > ul' that has this attribute: 
{flex-wrap: wrap} so that it will be more responsive? thanks

**Comment by HerbertHe** [comment]
Update to the latest version, it has been solved

**Comment by HerbertHe** [comment]
![image](https://user-images.githubusercontent.com/30955264/79040533-c5a35b80-7c1b-11ea-9aaf-411322e42b88.png)

**Comment by HerbertHe** [comment]
If you find again, please leave the version

**Comment by lishenyu16** [comment]
hi, for 2.3.2 version, I see the issue is still there like   
![image](https://user-images.githubusercontent.com/16713047/79051920-c8845900-7be7-11ea-9594-5661dc8abd0b.png)
For screen width >900 width, it becomes like this.

**Comment by lishenyu16** [comment]
add a {flex-wrap: wrap} to the .ul class will solve this issue I think.

**Comment by HerbertHe** [comment]
ok, I will fix this soon.

**Comment by HerbertHe** [comment]
Please update to the latest version, and check if it is ok

**Comment by lishenyu16** [comment]
yes it's not overflowing out of the box now, it's now looking like this, it may be optimized later when you have plenty of time to do so
![image](https://user-images.githubusercontent.com/16713047/79095139-7be76d80-7d0e-11ea-90bc-2070808347fa.png)
